# Generated by Django 2.2.6 on 2019-10-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matkon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('sections', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('prologue', models.TextField(blank=True, null=True)),
                ('prep_time', models.CharField(max_length=120)),
                ('cook_time', models.CharField(max_length=120)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
