# Generated by Django 2.2.6 on 2019-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkonim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkon',
            name='cook_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='matkon',
            name='prep_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
