# Generated by Django 2.2.6 on 2019-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkonim', '0002_auto_20191004_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrepTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='matkon',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='matkon',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='matkon',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='matkon',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='matkon',
            name='prep_time',
        ),
        migrations.AddField(
            model_name='matkon',
            name='category',
            field=models.ManyToManyField(to='matkonim.Category'),
        ),
        migrations.AddField(
            model_name='matkon',
            name='difficulty',
            field=models.ManyToManyField(to='matkonim.Difficulty'),
        ),
        migrations.AddField(
            model_name='matkon',
            name='techniques',
            field=models.ManyToManyField(to='matkonim.Technique'),
        ),
        migrations.AddField(
            model_name='matkon',
            name='cook_time',
            field=models.ManyToManyField(to='matkonim.CookTime'),
        ),
        migrations.AddField(
            model_name='matkon',
            name='ingredients',
            field=models.ManyToManyField(to='matkonim.Ingredient'),
        ),
        migrations.AddField(
            model_name='matkon',
            name='prep_time',
            field=models.ManyToManyField(to='matkonim.PrepTime'),
        ),
    ]
